name: 🚀 Build Metadata

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # If you have a requirements.txt, uncomment:
      #      pip install -r requirements.txt

      - name: Run full pipeline
        run: |
          pwsh ./run_all.ps1

      - name: Commit and push generated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add 06_Metadata_And_Indexes/master_metadata.csv \
                  06_Metadata_And_Indexes/merged_metadata.csv \
                  06_Metadata_And_Indexes/dublin_core_metadata.csv
          git commit -m "Automated update: regenerated metadata CSVs" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
